version: '3'
services:
  talant-jenkins: 
    container_name: talant-jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  talant-centos:
    container_name: centos-ssh
    image: ktalant/centos-ssh
    build:
      context: centos-ssh
    networks:
      - net 

  samara-centos:
    container_name: samara-ssh
    image: ktalant/samara-ssh
    build:
      context: samara-centos
    networks:
      - net 
  db-host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=pass123"
    volumes:
      - $PWD/db_data:/var/lib/mysql 
    networks:
      - net
networks:
  net:
